#!/bin/bash

# create_script
# This script creates a new bash script, sets permissions and more
# Author: jimxshaw

# Is there an argument?
if [[ ! $1 ]]
then 
  echo "Missing argument"
  exit 1
fi

scriptname="$1"
dirname="./"
filename="${dirname}/${scriptname}"

if [[ -e $filename ]]
then
  echo "File ${filename} already exists"
  exit 1
fi

if type "$scriptname"
then
  echo "There is already a command with name ${scriptname}"
  exit 1
fi

# Check if directory exists
if [[ ! -d $dirname ]]
then 
  # if not: create the directory
  if mkdir "$dirname"
  then
    echo "created ${dirname}"
  else
    echo "Could not create ${dirname}."
    exit 1
  fi
fi

# Create a script with a single line
echo "#!/bin/bash" > "$filename"
# Add executable permission
chmod u+x "$filename"
# Open with editor
if [[ $EDITOR ]]
then 
  $EDITOR "$filename"
else
  echo "Script created; not starting editor because \$EDITOR is not set."
fi