#!/bin/bash

# Simple note-taking script
# Author: Shaw

# Get the date
date=$(date)

# Get the topic
topic="$1"

# Filename to write to
filename="./${topic}notes.txt"

# Ask user for input
read -p "Your note: " note

if [[ $note ]]
then
  echo "$date: $note" >> "$filename"
  echo "Note '$note' saved to $filename"
else
  echo "No input; note was not saved."
fi